name: gemma-benchmark
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=23.0.0
  - pytorch>=2.0.0
  - torchvision
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scikit-learn>=1.2.0
  - tqdm>=4.65.0
  - colorama>=0.4.6
  - pyyaml>=6.0
  - pytest>=7.3.0
  - black>=23.3.0
  - pip:
    - transformers>=4.30.0
    - datasets>=2.12.0
    - evaluate>=0.4.0
    - accelerate>=0.20.0
